### ISSUE TITLE
Feature request: skip to first occurence of char before change inner/outer

### ISSUE THREAD

**Issue by torgeir** [magnars/change-inner.el#7]
Mimic vim's `ci` and `ca` commands even closer by making `change-inner` and `change-outer` skip to the first occurence of the character on the current line before changing inner/outer.

Example with point marked as `|`

- Given `Tes|ting, "testing"`
- Triggering `change-inner` and inputting `"`
- Yields `Testing, "|"`

**Comment by magnars** [comment]
You can't blindly jump forward, or you'd jump out of the string you're inside. So this would take some sort of cleverness that change-inner currently isn't built for. It is now just a little wrapper around expand-region. Maybe it could work to jump forward and try again if expanding from the current position didn't find anything?

**Comment by torgeir** [comment]
Yes, I was thinking you only jump if expanding from the current position doesn't find anything (this is how `ci` and `ca` works as well), if that doesn't find anything either you're out of luck :)

**Comment by magnars** [comment]
Sånn! :smile:

**Comment by torgeir** [comment]
Og det er på melpa allerede - Rått! :beers:
